
###
POST http://localhost:80/token
Content-Type: application/json

{
  "MsgUid": "b-fdeaccff-e219-401b-bb3d-aaa508b40116",
  "PinName": "Image Folder",
  "Values":  "{\"Database\": \"Image_channel_separator\", \"Collection\": \"Image_channel_separator_b-8b0e36\", \"ObjectId\": \"60254938cf19c15519cdff71\"}",
  "TokenSeqStack": []
}

###
POST http://localhost:80/token
Content-Type: application/json

{
  "MsgUid": "b-fdeaccff-e219-401b-bb3d-aaa508b40116",
  "PinName": "Image Folder",
  "Values": "{\"Files\":\"[{\\\"FileName\\\":\\\"BalticLSC-f4f318-jeremy-bishop.jpg\\\",\\\"ObjectId\\\":\\\"60eff33e471fe405cb00e525\\\"},{\\\"FileName\\\":\\\"BalticLSC-cacd60-casey-horner.jpg\\\",\\\"ObjectId\\\":\\\"60eff33e471fe405cb00e526\\\"}]\",\"Database\":\"baltic_database_6da3faf5\",\"Collection\":\"baltic_collection_ff5c243c\"}",
  "TokenSeqStack": []
}
